# a simple makefile to call $dpt on #$prog

# define prog to be pknock1.dpt
prog = unrestricted_memops.dpt
# define dpt to be ../../dpt
dpt = ../../../dpt

# define a "run" target to call $dpt on $prog
run:
	$(dpt) $(prog)