# This vagrant file uses the lucidvm box, which you can build 
# in /lucidvm
Vagrant.configure(2) do |config|
  config.vm.box = "lucid" # bionic 64 doesn't work with serial disconnected...
  config.vm.hostname = "lucidvm"
  config.vm.synced_folder "../", "/lucid"
  config.vm.provider "virtualbox" do |vb|
    # disable the log for portability.
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    vb.cpus = "1"
    vb.memory = "4096" 
    # config.disksize.size = "40GB"
  end
end