all:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc cleanup_test.dpt ip_harness.p4 linker_config.json build -p4tapp template.p4tapp ;\
	}


salu_dedup:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc salu_dedup.dpt ip_harness.p4 linker_config.json build ;\
	}

memop_and:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc memop_and.dpt ip_harness.p4 linker_config.json build ;\
	}


shifts:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc shifts.dpt ip_harness.p4 linker_config.json build ;\
	}

casting:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc casting.dpt ip_harness.p4 linker_config.json build ;\
	}

conditional_set:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc conditional_set.dpt ip_harness.p4 linker_config.json build ;\
	}

regmates:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc regmates.dpt ip_harness.p4 linker_config.json build ;\
	}

layout:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc layout.dpt ip_harness.p4 linker_config.json build ;\
	}

ssa:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc ssa.dpt ip_harness.p4 linker_config.json build ;\
	}

sat_sub:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc sat_sub.dpt ip_harness.p4 linker_config.json build ;\
	}

range:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc range.dpt ip_harness.p4 linker_config.json build ;\
	}

or:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc or.dpt ip_harness.p4 linker_config.json build ;\
	}

events: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc events.dpt ip_harness.p4 linker_config.json build ;\
	}

arrays: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc arrays.dpt ip_harness.p4 linker_config.json build ;\
	}

bools: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc bools.dpt ip_harness.p4 linker_config.json build ;\
	}

nested: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc nested.dpt ip_harness.p4 linker_config.json build ;\
	}

args: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc args.dpt ip_harness.p4 linker_config.json build ;\
	}
ineqs: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc ineqs.dpt ip_harness.p4 linker_config.json build ;\
	}

fcns: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc functions.dpt ip_harness.p4 linker_config.json build ;\
	}
inbranch: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc inlined_branches.dpt ip_harness.p4 linker_config.json build ;\
	}

match: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc match.dpt ip_harness.p4 linker_config.json build ;\
	}

dup_stmts: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc dup_stmts.dpt ip_harness.p4 linker_config.json build ;\
	}

events_p4tapp: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc events.dpt ip_harness.p4 linker_config.json build -p4tapp template.p4tapp ;\
	}


