all:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc cleanup_test.dpt harness.p4 build -p4tapp template.p4tapp ;\
	}


memop_and:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc memop_and.dpt harness.p4 build ;\
	}


shifts:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc shifts.dpt harness.p4 build ;\
	}

casting:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc casting.dpt harness.p4 build ;\
	}

conditional_set:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc conditional_set.dpt harness.p4 build ;\
	}

regmates:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc regmates.dpt harness.p4 build ;\
	}

layout:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc layout.dpt harness.p4 build ;\
	}

ssa:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc ssa.dpt harness.p4 build ;\
	}

sat_sub:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc sat_sub.dpt harness.p4 build ;\
	}

range:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc range.dpt harness.p4 build ;\
	}

or:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc or.dpt harness.p4 build ;\
	}

events: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc events.dpt harness.p4 build ;\
	}

arrays: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc arrays.dpt harness.p4 build ;\
	}

bools: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc bools.dpt harness.p4 build ;\
	}

nested: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc nested.dpt harness.p4 build ;\
	}

args: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc args.dpt harness.p4 build ;\
	}
ineqs: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc ineqs.dpt harness.p4 build ;\
	}

fcns: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc functions.dpt harness.p4 build ;\
	}
inbranch: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc inlined_branches.dpt harness.p4 build ;\
	}

match: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc match.dpt harness.p4 build ;\
	}

dup_stmts: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc dup_stmts.dpt harness.p4 build ;\
	}

events_p4tapp: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc events.dpt harness.p4 build -p4tapp template.p4tapp ;\
	}


