all:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc cleanup_test.dpt ip_harness.p4 linker_config.json build -p4tapp template.p4tapp ;\
	}

hashing:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptf hashing.dpt ;\
	}

memop_complex:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptf memop_complex.dpt ;\
	}

memop:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptf memop.dpt ;\
	}

param_branching:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptf param_branching.dpt ;\
	}

main:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc main.dpt ip_harness.p4 linker_config.json build;\
	}


identity_hash:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc identity_hash.dpt ip_harness.p4 linker_config.json build;\
	}


concat:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc concat.dpt ip_harness.p4 linker_config.json build;\
	}


inlining:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc inlining.dpt ip_harness.p4 linker_config.json build;\
	}


xor:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc xor.dpt ip_harness.p4 linker_config.json build;\
	}


slicing:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc slicing.dpt ip_harness.p4 linker_config.json build;\
	}

multi_events:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc multi_events.dpt ip_harness.p4 linker_config.json build;\
	}


salu_dedup:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc salu_dedup.dpt ip_harness.p4 linker_config.json build ;\
	}

memop_and:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc memop_and.dpt ip_harness.p4 linker_config.json build ;\
	}


shifts:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc shifts.dpt ip_harness.p4 linker_config.json build ;\
	}

casting:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc casting.dpt ip_harness.p4 linker_config.json build ;\
	}

conditional_set:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc conditional_set.dpt ip_harness.p4 linker_config.json build ;\
	}

regmates:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc regmates.dpt ip_harness.p4 linker_config.json build ;\
	}

layout:
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc layout.dpt ip_harness.p4 linker_config.json build ;\
	}

ssa:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc ssa.dpt ip_harness.p4 linker_config.json build ;\
	}

sat_sub:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc sat_sub.dpt ip_harness.p4 linker_config.json build ;\
	}

range:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc range.dpt ip_harness.p4 linker_config.json build ;\
	}

or:  
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc or.dpt ip_harness.p4 linker_config.json build ;\
	}

events: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc events.dpt ip_harness.p4 linker_config.json build ;\
	}

arrays: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc arrays.dpt ip_harness.p4 linker_config.json build ;\
	}

bools: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc bools.dpt ip_harness.p4 linker_config.json build ;\
	}

nested: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc nested.dpt ip_harness.p4 linker_config.json build ;\
	}

args: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc args.dpt ip_harness.p4 linker_config.json build ;\
	}
ineqs: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc ineqs.dpt ip_harness.p4 linker_config.json build ;\
	}

fcns: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc functions.dpt ip_harness.p4 linker_config.json build ;\
	}
inbranch: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc inlined_branches.dpt ip_harness.p4 linker_config.json build ;\
	}

match: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc match.dpt ip_harness.p4 linker_config.json build ;\
	}

dup_stmts: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc dup_stmts.dpt ip_harness.p4 linker_config.json build ;\
	}

events_p4tapp: 
	{ \
	cd ../../ ;\
	make ;\
	cd - ;\
	../../dptc events.dpt ip_harness.p4 linker_config.json build -p4tapp template.p4tapp ;\
	}


